package creational_design_patterns.Abstrac_Factory_Method.Concrete_Factory.DebrisField;

import creational_design_patterns.Abstrac_Factory_Method.Abstract_Factory.ObstacleFactory;

public abstract class DebrisFieldFactory extends ObstacleFactory
{

}
